In [1]:
# pip install qdrant-client
# pip install sentence-transformers

import os

import numpy as np
import pandas as pd

from openai import OpenAI
from qdrant_client import QdrantClient
from qdrant_client.models import VectorParams, Distance, PointStruct

In [2]:
client_qdrant = QdrantClient(
    url=os.environ["QDRANT_URL"],
    api_key=os.environ["QDRANT_API_KEY"],
)

In [3]:
client_openai = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

In [4]:
index_name = "ppgegc_qa_method"
dimensions = 1536

In [5]:
def histogram(classes:list, k:int):
    result = {}
    ctr=1
    for value, key in sorted(((classes.count(e), e) for e in set(classes)), reverse=True):
        if (ctr > k): break
        result[key] = value
        ctr+=1
    return result

In [6]:
def process_result(accuracy_dict, k, n, type):
    index = "{}-{}-{}".format(k,n,type)
    if (index in accuracy_dict):
        accuracy_dict[index] = accuracy_dict.get(index) + 1
    else:
        accuracy_dict[index] = 1

In [7]:
def get_process_result(accuracy_dict, k, n, type):
    index = "{}-{}-{}".format(k,n,type)
    if (index in accuracy_dict):
        return accuracy_dict[index]
    else:
        return 0

In [8]:
def print_process_result(accuracy_dict, k_list, n_list):
    for k in k_list:
        for n in n_list:
            positive = get_process_result(accuracy_dict, k, n, 'positive')
            negative = get_process_result(accuracy_dict, k, n, 'negative')
            accuracy = positive / (positive + negative)
            print("k={} - n={} - Positive: {} - Negative: {} - "
                "Accuracy: {} ".format(k,n,positive,negative,accuracy))

In [9]:
def transform_process_result(accuracy_dict, k_list, n_list):
    matrix = np.zeros((len(k_list), len(n_list)))
    i = j = 0
    for k in k_list:
        j=0
        for n in n_list:
            positive = get_process_result(accuracy_dict, k, n, 'positive')
            negative = get_process_result(accuracy_dict, k, n, 'negative')
            accuracy = positive / (positive + negative)
            matrix[i][j] = accuracy
            j+=1
        i+=1
    return matrix

In [10]:
#Method to approximate search
def search(vector):
    hits = client_qdrant.search(
        collection_name=index_name,
        query_vector=vector,
        limit=105 # 20, 50 e 100
    )
    return hits

In [13]:
PATH = "/home/thehprogrammer/Projects/python/qa-method/data/data.csv"

In [14]:
# Abrir csv em um dataframe
df = pd.read_csv(PATH)
df

,modalidade,autor,titulo,tipo,area_de_concentracao,ano_de_publicacao,local,orientador,coorientador,resumo,palavras_chave,abstract,keywords,introducao,conclusao,embedding,x,y,z
0,treino,Jorge Ivan Hmeljevski,Modelo para Sistemas de Supervisão de Mercado ...,tese,Engenharia do Conhecimento,2021,Florianópolis,"Prof. José Leomar Todesco, Dr.","Prof. Alexandre Leopoldo Gonçalves, Dr.",A confiança na higidez dos mercados de capitai...,"['Mercado de Capitais', 'Mercado de Valores Mo...",The confidence in the integrity of capital mar...,"['Capital market', 'Securities Market', 'Marke...",{'contextualizacao': 'O mercado de capitais é ...,O modelo elaborado nest a pesquisa envolveu a ...,"[0.02262425608932972, 0.06360490620136261, 0.0...",-0.174124,0.159395,-0.060768
1,treino,IVAM GALVÃO FILHO,FRACTUS: APLICATIVO PARA APRENDIZAGEM DE FRAÇÕES,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Profª. Vania Ribas Ulbricht, Drª.","Profª. Elisa Maria Pivetta, Drª.",O objetivo principal desta pesquisa foi o dese...,"['Objetos de Aprendizagem.', 'Frações.', 'Apli...",The main objective of this research was the de...,"['Learning Objects.', 'Fractions.', 'App for L...",{'contextualizacao': 'O sistema educacional br...,O trabalho realizado pela organização TODOS PE...,"[-0.006245349999517202, 0.065089151263237, 0.0...",0.143998,0.263873,-0.055491
2,treino,MÁRCIO CRESCENCIO,MODELO DE UMA REDE COLABORATIVA SUPORTADA POR ...,tese,Engenharia do Conhecimento,2022,Florianópolis,"Prof. Alexandre Augusto Biz , Dr.","Prof. José Leomar Todesco , Dr.",A convergência entre o turismo e a cultura atr...,"['Sítios de Patrimônio Mundial', 'Gestão do tu...",The convergence between tourism and culture th...,"['World Heritage Sites', 'Tourism management',...",{'contextualizacao': 'O turismo se tornou uma ...,Esta tese identificou que o turismo possui um ...,"[0.024945586919784546, 0.04501194879412651, 0....",-0.111669,-0.167909,-0.015695
3,treino,Roseli Honorio,MODELO CONCEITUAL DE GOVERNANÇA DE DADOS COMO ...,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Prof. João Artur de Souza, Dr.","Profa. Patrícia de Sá Freire, Dra.",A humanidade passou por transformações e revol...,"['Governança de Dados', 'Governança do Conheci...",Humanity has undergone transformations and rev...,"['Data Governance', 'Knowledge Governance', 'F...",{'contextualizacao': 'A sociedade está atraves...,"Na Ind ústria 4.0 e Sociedade 5.0, as organiza...","[0.05032069981098175, 0.051356106996536255, 0....",-0.229669,0.045873,-0.059402
4,treino,José Tadeu Silva,Análise da contribuição da engenharia do conhe...,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Prof. Fernando A. Ostuni Gauthier, Dr.","Prof. Marcelo Macedo, Dr.",A presente dissertação aborda as questões emer...,"['comércio eletrônico', 'modelo de análise', '...",The present dissertation addresses the emergin...,"['e-commerce', 'analysis model', 'knowledge en...",{'contextualizacao': 'De acordo com Lemos (200...,A partir do objetivo geral de analisar as cont...,"[-0.0012473083334043622, 0.044789645820856094,...",-0.195246,0.141014,0.098894
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,treino,Rosani Cesário Pereira,Competências essenciais dos pregoeiros: um est...,dissertação,Gestão do Conhecimento,2023,Florianópolis,"Prof.a Édis Mafra Lapolli, Dr a.","Prof.a Gertrudes A. Dandolini , Dra.",O modelo de gestão que vem se consolidando na ...,"['competências', 'competências essenciais', 'p...",The management model that has been consolidati...,"['competencies', 'essential competencies', 'pu...","{'contextualizacao': 'A autora, Rosani Cesário...",A pesquisa conclui que as competências essenci...,"[0.03604484349489212, 0.046274762600660324, 0....",-0.049497,-0.208519,-0.222047
146,treino,Fabíola Provensi,Gestão do Conhecimento e Cultura de Segurança ...,dissertação,Gestão do Conhecimento,2023,Florianópolis,"Prof. Eduardo Juan Soriano Sierra, Dr.","Prof. Neri Dos Santos, Dr.","No âmbito deste estudo, no que tange à Cultura...","['gestão do conhecimento', 'cultura de seguran...","In the scope of this study, regarding Safety C...","['knowledge management', 'safety culture', 'oc...",{'contextualizacao': 'A Saúde e Segurança no T...,O estudo realizado foi enriquecedor e motivado...,"[0.039430100470781326, 0.055613141506910324, 0...",-0.123317,-0.074993,-0.123015
147,treino,Maria Carolina Milani Caldas Sartor,Gestão feminina: a experiência de mulheres que...,tese,Gestão do Conhecimento,2023,Florianópolis,"Prof.a Édis Mafra Lapolli, Dra.","Prof.a Inara A. V. Willerding, Dra.",A entrada da mulher no mercado de trabalho e a...,"['gestão feminina', 'empoderamento da mulher',...",The entry of women into the labor market and t...,"['gender', 'women', 'entrepreneurship', 'knowl...",{'contextualizacao': 'A presente pesquisa visa...,"A presente pesquisa, realizada com o objetivo ...","[0.056130435317754745, 0.025203583762049675, 0...",-0.002209,-0.331049,-0.153390
148,treino,Sergio Luiz Gargioni,MODELO OPERACIONAL DE EDUCAÇÃO CONTINUADA PARA...,tese,Gestão do Conhecimento,2023,Florianópolis – SC,"Professor Neri dos Santos, Dr. Ing.","Professor Gregório Jean Varvakis Rados, Dr. Ing.",Este trabalho de tese apresenta um modelo oper...,"['Educação em Engenharia', 'Aprendizagem por C...",This thesis presents an operational model of c...,"['Engineering Education', 'Competency -Based L...",{'contextualizacao': 'O problema de pesquisa a...,Embora exista sempre espaço para pensar que co...,"[0.018794536590576172, 0.06826724857091904, -0...",0.021588,0.119867,0.174279
149,treino,Edegilson de Souza,A COMPLEXIDADE COMO SUPORTE À MODELAGEM DE COM...,tese,Gestão do Conhecimento,2023,Florianópolis,"Prof. Francisco Antonio Pereira Fialho, Dr.","Profa. Luciane Maria Fadel, Dra.",A implementação das novas metodologias de ensi...,"['Competências Docentes.', 'Práticas de Ensino...",The implementation of new teaching methodologi...,"['Teaching Competencies.', 'Teaching Practices...",{'contextualizacao': 'A educação do século 21 ...,A abordagem inovadora proposta neste estudo of...,"[0.04360678791999817, 0.05723390728235245, -0....",0.092158,0.018886,0.115306

In [15]:
# Contagem deve se tornar o id
df["id"] = df.index

# Id como index
df.set_index("id", inplace=True)

df.head()

,modalidade,autor,titulo,tipo,area_de_concentracao,ano_de_publicacao,local,orientador,coorientador,resumo,palavras_chave,abstract,keywords,introducao,conclusao,embedding,x,y,z
id,,,,,,,,,,,,,,,,,,,
0,treino,Jorge Ivan Hmeljevski,Modelo para Sistemas de Supervisão de Mercado ...,tese,Engenharia do Conhecimento,2021,Florianópolis,"Prof. José Leomar Todesco, Dr.","Prof. Alexandre Leopoldo Gonçalves, Dr.",A confiança na higidez dos mercados de capitai...,"['Mercado de Capitais', 'Mercado de Valores Mo...",The confidence in the integrity of capital mar...,"['Capital market', 'Securities Market', 'Marke...",{'contextualizacao': 'O mercado de capitais é ...,O modelo elaborado nest a pesquisa envolveu a ...,"[0.02262425608932972, 0.06360490620136261, 0.0...",-0.174124,0.159395,-0.060768
1,treino,IVAM GALVÃO FILHO,FRACTUS: APLICATIVO PARA APRENDIZAGEM DE FRAÇÕES,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Profª. Vania Ribas Ulbricht, Drª.","Profª. Elisa Maria Pivetta, Drª.",O objetivo principal desta pesquisa foi o dese...,"['Objetos de Aprendizagem.', 'Frações.', 'Apli...",The main objective of this research was the de...,"['Learning Objects.', 'Fractions.', 'App for L...",{'contextualizacao': 'O sistema educacional br...,O trabalho realizado pela organização TODOS PE...,"[-0.006245349999517202, 0.065089151263237, 0.0...",0.143998,0.263873,-0.055491
2,treino,MÁRCIO CRESCENCIO,MODELO DE UMA REDE COLABORATIVA SUPORTADA POR ...,tese,Engenharia do Conhecimento,2022,Florianópolis,"Prof. Alexandre Augusto Biz , Dr.","Prof. José Leomar Todesco , Dr.",A convergência entre o turismo e a cultura atr...,"['Sítios de Patrimônio Mundial', 'Gestão do tu...",The convergence between tourism and culture th...,"['World Heritage Sites', 'Tourism management',...",{'contextualizacao': 'O turismo se tornou uma ...,Esta tese identificou que o turismo possui um ...,"[0.024945586919784546, 0.04501194879412651, 0....",-0.111669,-0.167909,-0.015695
3,treino,Roseli Honorio,MODELO CONCEITUAL DE GOVERNANÇA DE DADOS COMO ...,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Prof. João Artur de Souza, Dr.","Profa. Patrícia de Sá Freire, Dra.",A humanidade passou por transformações e revol...,"['Governança de Dados', 'Governança do Conheci...",Humanity has undergone transformations and rev...,"['Data Governance', 'Knowledge Governance', 'F...",{'contextualizacao': 'A sociedade está atraves...,"Na Ind ústria 4.0 e Sociedade 5.0, as organiza...","[0.05032069981098175, 0.051356106996536255, 0....",-0.229669,0.045873,-0.059402
4,treino,José Tadeu Silva,Análise da contribuição da engenharia do conhe...,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Prof. Fernando A. Ostuni Gauthier, Dr.","Prof. Marcelo Macedo, Dr.",A presente dissertação aborda as questões emer...,"['comércio eletrônico', 'modelo de análise', '...",The present dissertation addresses the emergin...,"['e-commerce', 'analysis model', 'knowledge en...",{'contextualizacao': 'De acordo com Lemos (200...,A partir do objetivo geral de analisar as cont...,"[-0.0012473083334043622, 0.044789645820856094,...",-0.195246,0.141014,0.098894

In [16]:
import ast

df['introducao_dict'] = df['introducao'].apply(ast.literal_eval)

# Depois, crie as novas colunas extraindo os valores do dicionário
df['introducao_contextualizacao'] = df['introducao_dict'].apply(lambda x: x.get('contextualizacao', ''))
df['introducao_problematica'] = df['introducao_dict'].apply(lambda x: x.get('problematica', ''))
df['introducao_ineditismo'] = df['introducao_dict'].apply(lambda x: x.get('ineditismo', ''))
df['introducao_contribuicao'] = df['introducao_dict'].apply(lambda x: x.get('contribuição', ''))

# Remova a coluna temporária
df.drop(columns=['introducao_dict'], inplace=True)

df.head()

,modalidade,autor,titulo,tipo,area_de_concentracao,ano_de_publicacao,local,orientador,coorientador,resumo,...,introducao,conclusao,embedding,x,y,z,introducao_contextualizacao,introducao_problematica,introducao_ineditismo,introducao_contribuicao
id,,,,,,,,,,,,,,,,,,,,,
0,treino,Jorge Ivan Hmeljevski,Modelo para Sistemas de Supervisão de Mercado ...,tese,Engenharia do Conhecimento,2021,Florianópolis,"Prof. José Leomar Todesco, Dr.","Prof. Alexandre Leopoldo Gonçalves, Dr.",A confiança na higidez dos mercados de capitai...,...,{'contextualizacao': 'O mercado de capitais é ...,O modelo elaborado nest a pesquisa envolveu a ...,"[0.02262425608932972, 0.06360490620136261, 0.0...",-0.174124,0.159395,-0.060768,O mercado de capitais é fundamental para o cre...,"Os SSM, de maneira geral, usam os dado s prove...","De maneira inédita, portanto, este trabalho pa...","A contribuição desta pesquisa, portanto, está ..."
1,treino,IVAM GALVÃO FILHO,FRACTUS: APLICATIVO PARA APRENDIZAGEM DE FRAÇÕES,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Profª. Vania Ribas Ulbricht, Drª.","Profª. Elisa Maria Pivetta, Drª.",O objetivo principal desta pesquisa foi o dese...,...,{'contextualizacao': 'O sistema educacional br...,O trabalho realizado pela organização TODOS PE...,"[-0.006245349999517202, 0.065089151263237, 0.0...",0.143998,0.263873,-0.055491,O sistema educacional brasileiro passa por uma...,A deficiência na aprendizagem nas escolas de e...,,
2,treino,MÁRCIO CRESCENCIO,MODELO DE UMA REDE COLABORATIVA SUPORTADA POR ...,tese,Engenharia do Conhecimento,2022,Florianópolis,"Prof. Alexandre Augusto Biz , Dr.","Prof. José Leomar Todesco , Dr.",A convergência entre o turismo e a cultura atr...,...,{'contextualizacao': 'O turismo se tornou uma ...,Esta tese identificou que o turismo possui um ...,"[0.024945586919784546, 0.04501194879412651, 0....",-0.111669,-0.167909,-0.015695,O turismo se tornou uma das maiores indústrias...,"A convergência entre o turismo e a cultura, at...",O reconhecimento de PM atrai turistas adiciona...,Esses elementos de ligação do desenvolvimento ...
3,treino,Roseli Honorio,MODELO CONCEITUAL DE GOVERNANÇA DE DADOS COMO ...,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Prof. João Artur de Souza, Dr.","Profa. Patrícia de Sá Freire, Dra.",A humanidade passou por transformações e revol...,...,{'contextualizacao': 'A sociedade está atraves...,"Na Ind ústria 4.0 e Sociedade 5.0, as organiza...","[0.05032069981098175, 0.051356106996536255, 0....",-0.229669,0.045873,-0.059402,A sociedade está atravessando um momento de mu...,É nesse contexto que a Governanç a do Conhecim...,,
4,treino,José Tadeu Silva,Análise da contribuição da engenharia do conhe...,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Prof. Fernando A. Ostuni Gauthier, Dr.","Prof. Marcelo Macedo, Dr.",A presente dissertação aborda as questões emer...,...,{'contextualizacao': 'De acordo com Lemos (200...,A partir do objetivo geral de analisar as cont...,"[-0.0012473083334043622, 0.044789645820856094,...",-0.195246,0.141014,0.098894,"De acordo com Lemos (2003), sob qualquer aspec...","Para Vilaça e Araújo (2016), o conhecimento so...",,

In [17]:
# Criar o df apenas com os dados que tenham a modalidade treino
df_test = df[df['modalidade'] == 'teste']
df_test

,modalidade,autor,titulo,tipo,area_de_concentracao,ano_de_publicacao,local,orientador,coorientador,resumo,...,introducao,conclusao,embedding,x,y,z,introducao_contextualizacao,introducao_problematica,introducao_ineditismo,introducao_contribuicao
id,,,,,,,,,,,,,,,,,,,,,
29,teste,CLÁUDIO DE LIMA,REDES COLABORATIVAS COMO DINÂMICA DE INTERNACI...,tese,Engenharia do Conhecimento,2023,Florianópolis,"Prof. Rogério Cid Bastos , Dr.","Prof. Gregório J. Varvakis Rados, Dr.",As instituições de educação superior precisam ...,...,{'contextualizacao': 'As universidades têm bus...,Esta tese desenvolveu um Modelo de Avaliação d...,"[0.03478163480758667, 0.04431023448705673, 0.0...",-0.054975,0.137685,0.038244,As universidades têm buscado diferentes inicia...,"Por es ses motivos, Palacios -Callender e Robe...",Cabe destacar que a coautoria é considerada um...,"Com base no presente problema de pesquisa, sin..."
30,teste,Rafael Maia Pinto,Detecção de erros e fraudes em gastos públicos...,dissertação,Engenharia do Conhecimento,2023,Florianópolis,"Profa. Lia Caetano Bastos, Dra.","Prof. Rogério Cid Bastos, Dr.",A Constituição Federal estabelece limites míni...,...,{'contextualizacao': 'A Emenda Constitucional ...,À medida que a quantidade e complexidade das t...,"[-0.03038318268954754, 0.02694006636738777, 0....",-0.052560,0.204372,-0.242773,"A Emenda Constitucional 29 (BRASIL, 2000) à Co...","Todos os anos, são gerados milhões de lançamen...",,
31,teste,Elpídio Ribeiro Neves,Sistema sociotécnico de Integração de Modelos ...,tese,Engenharia do Conhecimento,2022,Florianópolis,"Prof. Paulo Maurício Selig, Dr.","Prof. Neri dos Santos, Dr.","As universidades, como organizações complexas,...",...,{'contextualizacao': 'Uma organização é mais q...,"Ao final deste trabalho, apresentam -se as con...","[-0.005148055963218212, 0.045625243335962296, ...",-0.077304,0.032610,-0.028912,Uma organização é mais que um conjunto de bens...,"Em particular, em relaç ão às universidades, c...",Os estudos realizados demonstram que o que ex...,"Este trabalho propõe um artefato, o Sistema SA..."
32,teste,Fernando Ferreira Aguiar,Framework para Criação e Manutenção de Bases d...,tese,Engenharia do Conhecimento,2023,Florianópolis,Prof. Dr. Marcelo Macedo,Prof. Dr. Denilson Sell,A presente tese aborda a problemática das base...,...,{'contextualizacao': 'A inovação impulsiona o ...,"A presente tese, portanto, contribuiu para o c...","[-0.018457775935530663, 0.0481286495923996, 0....",-0.175368,0.130818,0.090165,"A inovação impulsiona o desenvolvimento, trans...",No âmbito da escalabilidade operacional dentro...,,
33,teste,Rudger Nowasky do Nascimento Taxweiler,Framework de Ciência de Dados e Engenharia d...,tese,Engenharia do Conhecimento,2023,Florianópolis,"Denilson Sell, Dr.","Roberto Carlos dos Santos Pacheco, Dr.",A ciência brasileira está fortemente ligada à ...,...,{'contextualizacao': 'A ciência brasileira est...,"O framework ACDK, com base na teoria do Capit...","[0.0138176828622818, 0.06415273994207382, 0.01...",-0.100820,0.090234,0.066427,A ciência brasileira está fortemente ligada à ...,Explorar as informações dos egressos não é alg...,"Na literatura, é possível encontrar diversos t...","Além disso, a própria adoção da metodologia de..."
34,teste,Ricardo Alexandre Diogo,Modelo Conceitual para Formulação de Diretrize...,tese,Engenharia do Conhecimento,2023,Florianópolis,"Prof. Neri dos Santos, Dr.","Prof. Eduardo de Freitas Rocha Loures, Dr.",O fenômeno da Transformação Digital tem trazid...,...,{'contextualizacao': 'A Transformação Digital ...,"O objetivo geral desta tese, de propor um Mode...","[0.02255619876086712, 0.04089098423719406, -0....",-0.025043,0.121479,0.178046,A Transformação Digital da educação tem como p...,A Educação em Engenharia refere-se ao processo...,Apesar de haver na literatura uma proposta de ...,A necessidade de elicitar o conhecimento nos p...
35,teste,Rangel Machado Simon,Educação digital superior: desenvolvendo as co...,tese,Engenharia do Conhecimento,2023,Florianópolis,"Fernando José Spanhol, Dr.","Márcio Vieira de Souza, Dr.",Este trabalho propõe um modelo conceitual de c...,...,"{'contextualizacao': 'A evolução humana, impul...",A pesquisa evidenciou a necessidade de revisão...,"[0.03495481237769127, 0.04082000255584717, -0....",0.061980,0.100539,0.138580,"A evolução humana, impulsionada pelo crescimen...",A sociedade do conhecimento exige indivíduos c...,A necessidade de reorganizar a matriz curricul...,"O modelo conceitual proposto, ao identificar a..."
36,teste,Lodacir Rodrigo Silva da Rosa,Assistente Virtual Baseado em Conhecimento no ...,dissertação,Engenharia do Conhecimento,2023,Florianópolis,"Prof. Fernando Álvaro Ostuni Gauthier, Dr.","Prof. Vinicius Faria Culmant Ramos, Dr.",O trabalho tem como objetivo o desenvolvimento...,...,{'contextualizacao': 'Diversas instituições de...,Atualmente muito se discute sobre a importânci...,"[-0.01662576012313366, 0.05906371772289276, 0....",0.036523,0.256258,-0.029272,Diversas instituições de ensino desempenham um...,"A falta de atendimento no formato presencial, ...",,
37,teste,Letícia Silveira Artese,MODELO DE DESCOBERTA DE CONHECIMENTO EM TEXTO ...,tese,Engenharia do Conhecimento,2023,Florianópolis,"Prof. Alexandre Leopoldo Gonçalves, Dr.","Prof. José Leomar Todesco, Dr.\nCoorientador e...",Sinais fracos são fragmentos de informação que...,...,{'contextualizacao': 'O século XXI apresenta u...,A incerteza ocasionada pelo desenvolvimento ac...,"[0.01791909709572792, 0.05429352447390556, -0....",-0.096991,0.138803,0.123641,O século XXI apresenta uma conjunção de fatore...,"Como sociedade ocidental, os conceitos de ince...",A originalidade da pesquisa surge da abordagem...,Embora o interesse sobre informações acerca de...
38,teste,Larissa Mariany Freiberger Pereira,IAA/CD: Instrumento de Análise de Aderência da...,tese,Engenharia do Conhecimento,2023,Florianópolis,"Prof., Dr. Roberto Carlos dos Santos Pacheco","Prof., Dr. José Leomar Todesco",A Transformação Digital é um fenômeno que vem ...,...,{'contextualizacao': 'A Transformação Digital ...,"A presente pesquisa, guiada pelo método Design...","[0.012191844172775745, 0.02879239246249199, 0....",0.036948,0.037117,0.084439,A Transformação Digital é um fenômeno amplamen...,O ensino superior vem sendo impactado pela Tra...,A literatura sobre Transformação Digital em IE...,A pesquisa visa suprir a lacuna na literatura ...
39,teste,Thiago Zschornack,Processo de gestão de riscos integrado ao proc...,tese,Engenharia do Conhecimento,2023,Florianópolis,"Prof. João Artur de Souza, Dr.","Prof.(a) Gertrudes Aparecida Dandolini, Dra",O processo de inovar implica automaticamente e...,...,{'contextualizacao': 'A informação gerada pela...,A Engenharia do Conhecimento se propõe a instr...,"[0.0370074026286602, 0.062047798186540604, 0.0...",-0.268822,0.035850,0.073951,A informação gerada pela ciência e transformad...,Entre os principaisgapsexistentes e apontados ...,Com a análise destas abordagens na literatura ...,"Considerando este contexto, a originalidade de..."
40,teste,Luciano Zamperetti Wolski,Modelo de classificação de patentes baseado em...,tese,Engenharia do Conhecimento,2023,Florianópolis,Prof. Dr. Alexandre Leopoldo Gonçalves,Prof. Dr. José Leomar Todesco,Anualmente um grande volume de patentes é depo...,...,{'contextualizacao': 'Os pedidos de patentes c...,O volume dos dados nas bases de patente cresce...,"[0.0049549611285328865, 0.07595657557249069, -...",-0.109439,0.280486,-0.022288,"Os pedidos de patentes crescem anualmente e, s...",O desenvolvimento contínuo da tecnologia aumen...,"A partir da revisão integrativa da literatura,...","Sendo assim, a criação de um modelo que auxili..."
41,teste,Daniele Santos Raupp,Transformação Digital: Uma análise dos modelos...,dissertação,Engenharia do Conhecimento,2023,Florianópolis,"Prof. José Leomar Todesco, Dr.","Prof. Fernando Álvaro Ostuni Gauthier, Dr.",A Transformação Digital proporciona um oceano ...,...,"{'contextualizacao': 'Novos desafios, impactos...",Existem poucas abordagens validadas e testadas...,"[0.005690368823707104, 0.07581579685211182, 0....",-0.177725,-0.016565,0.176344,"Novos desafios, impactos e mudanças no equilíb...",A compreensão sobre a prontidão digital de uma...,,
42,teste,VALERIO JUNIOR PIANA,MÉTODO VOLTADO À RECOMENDAÇÃO DE TRATAMENTOS F...,dissertação,Engenharia do Conhecimento,2023,Florianópolis,Prof. Dr. Alexandre Leopoldo Gonçalves,Prof. Dr. João Artur de Souza,A fisioterapia tem testemunhado avanços signif...,...,{'contextualizacao': 'A aplicação de alternati...,"Na área da fisioterapia, enfrentar as SCIs é u...","[0.028286268934607506, 0.023664914071559906, 0...",0.073136,0.297490,0.057649,A aplicação de alternativas terapêuticas na ár...,"As SCIs, segundo Lilleyet al. (2020), causam p...",,
43,teste,Marcelo Ribeiro Vilas Boas,Proposta de um Modelo de Governança de dados a...,dissertação,Engenharia do Conhecimento,2024,Florianópolis,Drª Lia Caetano Bastos,Dr. Rogério Cid Bastos,Como a integração da Filosofia Lean e a Govern...,...,{'contextualizacao': 'Em uma organização como ...,As organizações necessitam encontrar formas de...,"[0.033567339181900024, 0.05495298281311989, -0...",-0.200011,-0.003944,-0.210357,Em uma organização como a Polícia Militar de M...,É nesse contexto que a Governança do Conhecime...,,
49,teste,Natana Souza Da Rosa,Diretrizes para o desenvolvimento de aplicaçõe...,tese,Mídia do Conhecimento,2023,Florianópolis,Prof. Drª. Vania Ribas Ulbricht,Dr. Tarcício Vanzin,"Na atual sociedade do conhecimento, o acesso à...",...,{'contextualizacao': 'A inserção das tecnologi...,Este estudo engloba três principais aspectos q...,"[0.042108841240406036, 0.049905143678188324, 0...",0.273608,0.196860,-0.095725,A inserção das tecnologias digitais no context...,A busca por soluções também deve ser lembrada...,A originalidade e a relevância desta pesquisa ...,"Este estudo visa contribuir com a criação, com..."
50,teste,Denise Ouriques Medeiros,"Cidades ideais: conhecimento, imaginação, utop...",tese,Mídia do Conhecimento,2022,Florianópolis,"Prof. Richard Perassi L. de Sousa, Dr.","Prof. Tarcísio Vanzin, Dr.","A imaginação é a instância dos sonhos, sejam o...",...,"{'contextualizacao': 'Neste texto, apresenta-s...",Recorda-se aqui que o objetivo geral deste est...,"[0.028719212859869003, 0.03422202542424202, 0....",0.097310,-0.150715,0.045768,"Neste texto, apresenta-se um estudo sobre moti...","De modo geral, este estudo é configurado a par...",A pesquisa desenvolvida na realização deste es...,A “análise exploratória” é um procedimento ini...
51,teste,Antônio Carlos Picalho,Das bibliotecas aos buscadores : testando técn...,dissertação,Mídia do Conhecimento,2023,Florianópolis,"Profa. Luciane Maria Fadel, Dra.","Prof. Alexandre Leopoldo Gonçalves, Dr.",Pesquisar on-line é uma atividade presente na ...,...,{'contextualizacao': 'A lógica na qual se apoi...,O sucesso de um processo de busca na internet ...,"[0.02095792442560196, 0.04992707073688507, -0....",0.095913,0.089143,-0.081743,A lógica na qual se apoia a formulação de uma ...,"Em pleno ano de 2023 , realizar uma pesquisa d...",,
52,teste,Luís Henrique Lindner,SmartSelf: Potencialidades do Smartphone na Ap...,tese,Mídia do Conhecimento,2023,Florianópolis,"Prof. Araci Hack Catapan, Dra.","Prof. Clarissa Stefani Teixeira, Dra.",A aprendizagem ao longo da vida tem sido tema ...,...,{'contextualizacao': 'A noção de que aprendemo...,"Esta tese contribui com uma agenda global, com...","[0.02832639031112194, 0.04729931056499481, -0....",0.247117,0.065447,0.155222,A noção de que aprendemos ao longo de toda a v...,"Em relação à riqueza de experiências, o cresce...",Revisões sistemáticas recentes na área de apre...,No que tange a relação específica entre smartp...
53,teste,Denise Maria Bezerra,"Pianismo, pianear e o processo de individuação...",tese,Mídia do Conhecimento,2023,Florianópolis,Prof. Dr. Francisco Antonio Pereira Fialho,Prof. Dr. Richard Perassi,"Tradicionalmente, a pesquisa científica sobre ...",...,{'contextualizacao': 'A pesquisa científica so...,"Nesta autoetnografia, eu contei como se deu a ...","[0.02594507671892643, 0.017680907621979713, 0....",0.263358,-0.075899,0.136456,A pesquisa científica sobre a formação do pian...,Percebe-se a necessidade de adotar uma abordag...,Esta tese inaugura na pesquisa científica no B...,A tese oferece dois grandes resultados: a auto...
54,teste,Nanci Cecília de Oliveira Veras,OS ATOS DA FALA E A COMUNICAÇÃO DA INTENCIONAL...,tese,Mídia do Conhecimento,2023,Florianópolis,"Prof.(a) Tarcísio Vanzin , Dr.","Prof.(a) Sílvio Serafim da Luz Filho , Dr.",Esta pesquisa objetiva analisar como os intérp...,...,"{'contextualizacao': 'Majoritariamente, a soci...","Nesta pesquisa, a partir da Teoria dos Atos de...","[0.04148716479539871, 0.03604365512728691, -0....",0.282535,-0.041142,-0.140502,"Majoritariamente, a sociedade tem como meio de...","Assim, tendo em vista a problemática apresenta...","No que se refere ao conhecimento, o aporte des...",Para que ocorra a constituição do conhecimento...
55,teste,Thiago da Silva Mota,FORMAÇÃO DE CONHECIMENTO PARA USUÁRIOS SURDOS ...,dissertação,Mídia do Conhecimento,2023,Florianópolis,"Professor Tarcísio Vanzin, Dr.","Professora Luciane Maria Fadel, Dra.",As Histórias em Quadrinhos são ferramentas com...,...,{'contextualizacao': 'Segundo último censo do ...,A presente dissertação teve como ponto de part...,"[0.05299258232116699, 0.059339266270399094, -0...",0.352402,0.024043,-0.124476,Segundo último censo do Instituto Brasileiro d...,"Como consequência da deficiência, os surdos po...",,
56,teste,Felipe de Matos Müller,Liderança em rede na educação e pesquisa inter...,tese,Mídia do Conhecimento,2023,Florianópolis,Prof. Dr. Márcio Vieira de Souza,Prof. Dr. rer. pol. Cristiano José Castro de A...,Dentro do cenário das instituições universitár...,...,{'contextualizacao': 'A literatura sobre lider...,A liderança em rede (network leadership) é um ...,"[0.02467869408428669, -0.013006062246859074, -...",0.081443,-0.223488,0.139112,A literatura sobre liderança coloca em foco um...,Mas o que significa dizer que a liderança é “e...,A pesquisa e a publicação científicas enfrenta...,A originalidade em textos científicos e técnic...
57,teste,Marisol da Silva Paz,Marketing do Conhecimento : O Uso da Plataform...,dissertação,Mídia do Conhecimento,2023,Florianópolis,"Profa. Luciane Maria Fadel, Dra.","Profa. Maria Collier de Mendonça, Dra.",Este estudo examina a relevância do marketing ...,...,{'contextualizacao': 'O conhecimento se tornou...,O estudo concluiu que a utilização do YouTube ...,"[0.0317179299890995, 0.06347991526126862, -0.0...",0.018133,-0.048240,-0.030420,O conhecimento se tornou um elemento crucial n...,"Apesar da importância do conhecimento, a comun...",,
58,teste,Cláudia Regina Damasceno Luciano,Aprendizagem significativa e cidadania: um est...,dissertação,Mídia do Conhecimento,2023,Florianópolis,"Profa. Araci Hack Catapan, Dra.","Prof. Márcio Vieira de Souza, Dr.",A presente pesquisa analisa o curso de formaçã...,...,{'contextualizacao': 'A pesquisa denominada “A...,"A atuação da Justiça Eleitoral é ampla, assim ...","[0.03942662104964256, 0.04009676352143288, -0....",0.248553,-0.070900,-0.218973,A pesquisa denominada “Aprendizagem significat...,"Nesse sentido, a pesquisa analisou a turma de ...",,
59,teste,Robson Santos da Silva,FRAMEWORK PARA DESENVOLVIMENTO DE COMPETÊNCIAS...,tese,Mídia do Conhecimento,2023,Florianópolis - SC,"Prof. José Fernando Spanhol, Dr.","Márcio Vieira de Souza, Dr.",A prestação de serviços de Atenção Primária à ...,...,"{'contextualizacao': 'O cenário global, confor...",O questionamento sobre como desenvolver as com...,"[0.039924073964357376, 0.0503561832010746, -0....",0.072234,0.000331,0.008545,"O cenário global, conforme Sá e Paixão (2016),...","Em 2022, o relatórioEducase Horizon Reportrati...",Ao serem analisados os dados obtidos pela SESA...,"Foram indagações, no entanto, cujas possíveis ..."
60,teste,William Cordeiro Costa,Conhecimento de artes visuais e mídia digital ...,dissertação,Mídia do Conhecimento,2023,Florianópolis,"Prof. Richard Perassi Luiz de Sousa, Dr.","Prof. João Bosco da Mota Alves, Dr.",Nesta dissertação é apresentado um estudo sobr...,...,"{'contextualizacao': 'De maneira geral, a part...","Na presente dissertação, buscou-se discutir a ...","[0.011389611288905144, 0.037097591906785965, 0...",0.366217,0.079476,-0.060989,"De maneira geral, a partir das últimas três dé...","De maneira crítica, observou-se que, apesar de...",,
61,teste,Ágatha Cristine Depiné,Participação Cidadã na Governança de Cidades I...,tese,Mídia do Conhecimento,2023,Florianópolis,"Prof. Tarcísio Vanzin, Dr.","Profa. Clarissa Teixeira, Dra.",O presente estudo se dedicou a investigar o fe...,...,"{'contextualizacao': ""O direito à cidade é um ...",O presente estudo buscou aprofundar o conhecim...,"[0.05212775617837906, 0.02319277822971344, 0.0...",-0.037805,-0.180775,-0.085518,O direito à cidade é um conceito político-filo...,"No cenário global contemporâneo, destacam-se r...","No conceito de cidade inteligente, a palavra “...",Acompanhando o movimento desta tipologia no Pa...
62,teste,Nicole Pasini Trevisol,MAPA DO CONHECIMENTO PARA ASSESSORIA DE COMUNI...,tese,Mídia do Conhecimento,2023,Florianópolis,Prof. Dr. Richard Perassi Luiz de Sousa,Profa. Dra. Maria José Baldessar,"Nesta tese, apresenta-se um estudo sobre a atu...",...,"{'contextualizacao': 'No Brasil, as instituiçõ...",O Mapa de Conhecimento para a Assessoria de Co...,"[0.002918870421126485, 0.042490024119615555, 0...",-0.003279,-0.165388,-0.213124,"No Brasil, as instituições públicas universitá...","Em geral, no âmbito das instituições públicas ...","Considera-se que, depois de obter, sistematiza...","Como foi anteriormente indicado, as assessoria..."
99,teste,Paulo Vitor Tavares,TRANSVÍDEO 4.0: UM FRAMEWORK ASSOCIANDO REMIDI...,tese,Mídia do Conhecimento,2023,Florianópolis,"Profa. Luciane Maria Fadel, PhD","Araci Hack Catapan, Dra.",Na Sociedade Digital a demanda por vídeo é alt...,...,{'contextualizacao': 'O Conhecimento tem sido ...,A pesquisa contribui para a discussão acadêmic...,"[0.01096787303686142, 0.04174438863992691, -0....",0.214562,0.025034,0.060010,O Conhecimento tem sido objeto de inúmeros est...,Na Sociedade Digit al a demanda por vídeo é al...,"Para verificar o ineditismo da pesquisa, foi r...","Para a ciência, a pesquisa vem contribuir para..."
100,teste,Kellyn Clyciane Mendes Rosa,LEAN LEADERSHIP: ATRIBUTOS IMPLÍCITOS DA LIDER...,dissertação,Gestão do Conhecimento,2023,Florianópolis,Cristiano José Castro de Almeida Cunha,Neri dos Santos,"O objetivo deste estudo foi compreender, a par...",...,{'contextualizacao': 'A busca pela eficiência ...,Esta pesquisa teve como objetivo geral compree...,"[-0.002697535092011094, 0.01856933906674385, -...",-0.059410,-0.133344,0.165292,A busca pela eficiência e pela produtividade é...,"Atualmente, muitas organizações estão interess...",,
101,teste,Adriana Veríssimo Karam Koleski,Metamodelo para implementação de transformação...,tese,Gestão do Conhecimento,2023,Florianópolis,"Prof. Roberto Carlos dos Santos Pacheco, Dr.","Prof. Neri dos Santos, Dr.",As transformações vividas no contexto da socie...,...,{'contextualizacao': 'Vivemos em um momento de...,Esta tese apresentou e discutiu o panorama das...,"[0.00021724043472204357, 0.016576694324612617,...",-0.009493,0.075419,0.240996,Vivemos em um momento de profundas transformaç...,As organizações em geral também vivenciam uma ...,O contexto é bastante complexo e desafiador. A...,Pesquisas sobre transformação digital na educa...

In [18]:
#Performs queries to group returned concentrarion area for each input dissertation or thesis
print("Index name: ",index_name)
k_list = [1,2,3]
n_list = [1,5,10,15,20]
accuracy_dict = {}
candidate = 105 # 50 e 100
ctr_hit = 0
hits_count = 0
positive = negative = 0
examiner_list = []
hit_list = []
ctr_queries = 0

for index, row in df_test.iterrows():
    ctr_queries+=1
    
    # Converta a string de embedding para uma lista de floats
    embedding = ast.literal_eval(row.embedding)

    hits = search(embedding)

    hit_list.clear()
    hits_count=0
    for hit in hits:
        hit_list.append(hit.payload['area_de_concentracao'])
        hits_count+=1

    print("Query id: "+str(ctr_queries)+" - area_de_concentracao: "+ row.area_de_concentracao  +" - Hits: "+str(hits_count))

    for k in k_list:
        for n in n_list:
            histogram_res = histogram(hit_list[:n], k)
            if (row.area_de_concentracao in histogram_res):
                process_result(accuracy_dict, k, n, 'positive')
            else:
                process_result(accuracy_dict, k, n, 'negative')

print_process_result(accuracy_dict, k_list, n_list)
print("Accuracy by k and n")
matrix = transform_process_result(accuracy_dict, k_list, n_list)
print(matrix)

Index name:  ppgegc_qa_method
Query id: 1 - area_de_concentracao: Engenharia do Conhecimento - Hits: 105
Query id: 2 - area_de_concentracao: Engenharia do Conhecimento - Hits: 105
Query id: 3 - area_de_concentracao: Engenharia do Conhecimento - Hits: 105
Query id: 4 - area_de_concentracao: Engenharia do Conhecimento - Hits: 105
Query id: 5 - area_de_concentracao: Engenharia do Conhecimento - Hits: 105
Query id: 6 - area_de_concentracao: Engenharia do Conhecimento - Hits: 105
Query id: 7 - area_de_concentracao: Engenharia do Conhecimento - Hits: 105
Query id: 8 - area_de_concentracao: Engenharia do Conhecimento - Hits: 105
Query id: 9 - area_de_concentracao: Engenharia do Conhecimento - Hits: 105
Query id: 10 - area_de_concentracao: Engenharia do Conhecimento - Hits: 105
Query id: 11 - area_de_concentracao: Engenharia do Conhecimento - Hits: 105
Query id: 12 - area_de_concentracao: Engenharia do Conhecimento - Hits: 105
Query id: 13 - area_de_concentracao: Engenharia do Conhecimento - Hits: 105
Query id: 14 - area_de_concentracao: Engenharia do Conhecimento - Hits: 105
Query id: 15 - area_de_concentracao: Engenharia do Conhecimento - Hits: 105
Query id: 16 - area_de_concentracao: Mídia do Conhecimento - Hits: 105
Query id: 17 - area_de_concentracao: Mídia do Conhecimento - Hits: 105
Query id: 18 - area_de_concentracao: Mídia do Conhecimento - Hits: 105
Query id: 19 - area_de_concentracao: Mídia do Conhecimento - Hits: 105
Query id: 20 - area_de_concentracao: Mídia do Conhecimento - Hits: 105
Query id: 21 - area_de_concentracao: Mídia do Conhecimento - Hits: 105
Query id: 22 - area_de_concentracao: Mídia do Conhecimento - Hits: 105
Query id: 23 - area_de_concentracao: Mídia do Conhecimento - Hits: 105
Query id: 24 - area_de_concentracao: Mídia do Conhecimento - Hits: 105
Query id: 25 - area_de_concentracao: Mídia do Conhecimento - Hits: 105
Query id: 26 - area_de_concentracao: Mídia do Conhecimento - Hits: 105
Query id: 27 - area_de_concentracao: Mídia do Conhecimento - Hits: 105
Query id: 28 - area_de_concentracao: Mídia do Conhecimento - Hits: 105
Query id: 29 - area_de_concentracao: Mídia do Conhecimento - Hits: 105
Query id: 30 - area_de_concentracao: Mídia do Conhecimento - Hits: 105
Query id: 31 - area_de_concentracao: Gestão do Conhecimento - Hits: 105
Query id: 32 - area_de_concentracao: Gestão do Conhecimento - Hits: 105
Query id: 33 - area_de_concentracao: Gestão do Conhecimento - Hits: 105
Query id: 34 - area_de_concentracao: Gestão do Conhecimento - Hits: 105
Query id: 35 - area_de_concentracao: Gestão do Conhecimento - Hits: 105
Query id: 36 - area_de_concentracao: Gestão do Conhecimento - Hits: 105
Query id: 37 - area_de_concentracao: Gestão do Conhecimento - Hits: 105
Query id: 38 - area_de_concentracao: Gestão do Conhecimento - Hits: 105
Query id: 39 - area_de_concentracao: Gestão do Conhecimento - Hits: 105
Query id: 40 - area_de_concentracao: Gestão do Conhecimento - Hits: 105
Query id: 41 - area_de_concentracao: Gestão do Conhecimento - Hits: 105
Query id: 42 - area_de_concentracao: Gestão do Conhecimento - Hits: 105
Query id: 43 - area_de_concentracao: Gestão do Conhecimento - Hits: 105
Query id: 44 - area_de_concentracao: Gestão do Conhecimento - Hits: 105
Query id: 45 - area_de_concentracao: Gestão do Conhecimento - Hits: 105
k=1 - n=1 - Positive: 30 - Negative: 15 - Accuracy: 0.6666666666666666
k=1 - n=5 - Positive: 27 - Negative: 18 - Accuracy: 0.6
k=1 - n=10 - Positive: 26 - Negative: 19 - Accuracy: 0.5777777777777777
k=1 - n=15 - Positive: 30 - Negative: 15 - Accuracy: 0.6666666666666666
k=1 - n=20 - Positive: 30 - Negative: 15 - Accuracy: 0.6666666666666666
k=2 - n=1 - Positive: 30 - Negative: 15 - Accuracy: 0.6666666666666666
k=2 - n=5 - Positive: 40 - Negative: 5 - Accuracy: 0.8888888888888888
k=2 - n=10 - Positive: 40 - Negative: 5 - Accuracy: 0.8888888888888888
k=2 - n=15 - Positive: 41 - Negative: 4 - Accuracy: 0.9111111111111111
k=2 - n=20 - Positive: 41 - Negative: 4 - Accuracy: 0.9111111111111111
k=3 - n=1 - Positive: 30 - Negative: 15 - Accuracy: 0.6666666666666666
k=3 - n=5 - Positive: 41 - Negative: 4 - Accuracy: 0.9111111111111111
k=3 - n=10 - Positive: 44 - Negative: 1 - Accuracy: 0.9777777777777777
k=3 - n=15 - Positive: 45 - Negative: 0 - Accuracy: 1.0
k=3 - n=20 - Positive: 45 - Negative: 0 - Accuracy: 1.0
Accuracy by k and n
[[0.66666667 0.6        0.57777778 0.66666667 0.66666667]
 [0.66666667 0.88888889 0.88888889 0.91111111 0.91111111]
 [0.66666667 0.91111111 0.97777778 1.         1.        ]]