In [3]:
# pip install qdrant-client
# pip install sentence-transformers

import pandas as pd
import os

from openai import OpenAI
from qdrant_client import QdrantClient
from qdrant_client.models import VectorParams, Distance, PointStruct

In [4]:
#client = QdrantClient(url="http://localhost:6333")

client_qdrant = QdrantClient(
    url="https://3e2646b6-b028-47c8-8f04-5e5e29bd47a9.europe-west3-0.gcp.cloud.qdrant.io:6333",
    api_key="fJBBXMwfzWIZcTjSbpJlCjeuE7VianH1eebazHhfCYqX1wsAHyq2Xg",
)

openai_api_key = os.environ.get("OPENAI_API_KEY")

In [5]:
client_openai = OpenAI(
  api_key="OPEN_AI_KEY"
)

In [6]:
PATH = "/home/thehprogrammer/Projects/python/qa-method/data.csv"

In [34]:
# Abrir csv em um dataframe
df = pd.read_csv(PATH)
df

,modalidade,autor,titulo,tipo,area_de_concentracao,ano_de_publicacao,local,orientador,coorientador,resumo,palavras_chave,abstract,keywords,introducao,conclusao,embedding,x,y,z
0,treino,Jorge Ivan Hmeljevski,Modelo para Sistemas de Supervisão de Mercado ...,tese,Engenharia do Conhecimento,2021,Florianópolis,"Prof. José Leomar Todesco, Dr.","Prof. Alexandre Leopoldo Gonçalves, Dr.",A confiança na higidez dos mercados de capitai...,"['Mercado de Capitais', 'Mercado de Valores Mo...",The confidence in the integrity of capital mar...,"['Capital market', 'Securities Market', 'Marke...",{'contextualizacao': 'O mercado de capitais é ...,O modelo elaborado nest a pesquisa envolveu a ...,"[0.02262425608932972, 0.06360490620136261, 0.0...",-0.174124,0.159395,-0.060768
1,treino,IVAM GALVÃO FILHO,FRACTUS: APLICATIVO PARA APRENDIZAGEM DE FRAÇÕES,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Profª. Vania Ribas Ulbricht, Drª.","Profª. Elisa Maria Pivetta, Drª.",O objetivo principal desta pesquisa foi o dese...,"['Objetos de Aprendizagem.', 'Frações.', 'Apli...",The main objective of this research was the de...,"['Learning Objects.', 'Fractions.', 'App for L...",{'contextualizacao': 'O sistema educacional br...,O trabalho realizado pela organização TODOS PE...,"[-0.006245349999517202, 0.065089151263237, 0.0...",0.143998,0.263873,-0.055491
2,treino,MÁRCIO CRESCENCIO,MODELO DE UMA REDE COLABORATIVA SUPORTADA POR ...,tese,Engenharia do Conhecimento,2022,Florianópolis,"Prof. Alexandre Augusto Biz , Dr.","Prof. José Leomar Todesco , Dr.",A convergência entre o turismo e a cultura atr...,"['Sítios de Patrimônio Mundial', 'Gestão do tu...",The convergence between tourism and culture th...,"['World Heritage Sites', 'Tourism management',...",{'contextualizacao': 'O turismo se tornou uma ...,Esta tese identificou que o turismo possui um ...,"[0.024945586919784546, 0.04501194879412651, 0....",-0.111669,-0.167909,-0.015695
3,treino,Roseli Honorio,MODELO CONCEITUAL DE GOVERNANÇA DE DADOS COMO ...,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Prof. João Artur de Souza, Dr.","Profa. Patrícia de Sá Freire, Dra.",A humanidade passou por transformações e revol...,"['Governança de Dados', 'Governança do Conheci...",Humanity has undergone transformations and rev...,"['Data Governance', 'Knowledge Governance', 'F...",{'contextualizacao': 'A sociedade está atraves...,"Na Ind ústria 4.0 e Sociedade 5.0, as organiza...","[0.05032069981098175, 0.051356106996536255, 0....",-0.229669,0.045873,-0.059402
4,treino,José Tadeu Silva,Análise da contribuição da engenharia do conhe...,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Prof. Fernando A. Ostuni Gauthier, Dr.","Prof. Marcelo Macedo, Dr.",A presente dissertação aborda as questões emer...,"['comércio eletrônico', 'modelo de análise', '...",The present dissertation addresses the emergin...,"['e-commerce', 'analysis model', 'knowledge en...",{'contextualizacao': 'De acordo com Lemos (200...,A partir do objetivo geral de analisar as cont...,"[-0.0012473083334043622, 0.044789645820856094,...",-0.195246,0.141014,0.098894
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,treino,Rosani Cesário Pereira,Competências essenciais dos pregoeiros: um est...,dissertação,Gestão do Conhecimento,2023,Florianópolis,"Prof.a Édis Mafra Lapolli, Dr a.","Prof.a Gertrudes A. Dandolini , Dra.",O modelo de gestão que vem se consolidando na ...,"['competências', 'competências essenciais', 'p...",The management model that has been consolidati...,"['competencies', 'essential competencies', 'pu...","{'contextualizacao': 'A autora, Rosani Cesário...",A pesquisa conclui que as competências essenci...,"[0.03604484349489212, 0.046274762600660324, 0....",-0.049497,-0.208519,-0.222047
146,treino,Fabíola Provensi,Gestão do Conhecimento e Cultura de Segurança ...,dissertação,Gestão do Conhecimento,2023,Florianópolis,"Prof. Eduardo Juan Soriano Sierra, Dr.","Prof. Neri Dos Santos, Dr.","No âmbito deste estudo, no que tange à Cultura...","['gestão do conhecimento', 'cultura de seguran...","In the scope of this study, regarding Safety C...","['knowledge management', 'safety culture', 'oc...",{'contextualizacao': 'A Saúde e Segurança no T...,O estudo realizado foi enriquecedor e motivado...,"[0.039430100470781326, 0.055613141506910324, 0...",-0.123317,-0.074993,-0.123015
147,treino,Maria Carolina Milani Caldas Sartor,Gestão feminina: a experiência de mulheres que...,tese,Gestão do Conhecimento,2023,Florianópolis,"Prof.a Édis Mafra Lapolli, Dra.","Prof.a Inara A. V. Willerding, Dra.",A entrada da mulher no mercado de trabalho e a...,"['gestão feminina', 'empoderamento da mulher',...",The entry of women into the labor market and t...,"['gender', 'women', 'entrepreneurship', 'knowl...",{'contextualizacao': 'A presente pesquisa visa...,"A presente pesquisa, realizada com o objetivo ...","[0.056130435317754745, 0.025203583762049675, 0...",-0.002209,-0.331049,-0.153390
148,treino,Sergio Luiz Gargioni,MODELO OPERACIONAL DE EDUCAÇÃO CONTINUADA PARA...,tese,Gestão do Conhecimento,2023,Florianópolis – SC,"Professor Neri dos Santos, Dr. Ing.","Professor Gregório Jean Varvakis Rados, Dr. Ing.",Este trabalho de tese apresenta um modelo oper...,"['Educação em Engenharia', 'Aprendizagem por C...",This thesis presents an operational model of c...,"['Engineering Education', 'Competency -Based L...",{'contextualizacao': 'O problema de pesquisa a...,Embora exista sempre espaço para pensar que co...,"[0.018794536590576172, 0.06826724857091904, -0...",0.021588,0.119867,0.174279
149,treino,Edegilson de Souza,A COMPLEXIDADE COMO SUPORTE À MODELAGEM DE COM...,tese,Gestão do Conhecimento,2023,Florianópolis,"Prof. Francisco Antonio Pereira Fialho, Dr.","Profa. Luciane Maria Fadel, Dra.",A implementação das novas metodologias de ensi...,"['Competências Docentes.', 'Práticas de Ensino...",The implementation of new teaching methodologi...,"['Teaching Competencies.', 'Teaching Practices...",{'contextualizacao': 'A educação do século 21 ...,A abordagem inovadora proposta neste estudo of...,"[0.04360678791999817, 0.05723390728235245, -0....",0.092158,0.018886,0.115306

In [35]:
# Contagem deve se tornar o id
df["id"] = df.index

# Id como index
df.set_index("id", inplace=True)

df.head()

,modalidade,autor,titulo,tipo,area_de_concentracao,ano_de_publicacao,local,orientador,coorientador,resumo,palavras_chave,abstract,keywords,introducao,conclusao,embedding,x,y,z
id,,,,,,,,,,,,,,,,,,,
0,treino,Jorge Ivan Hmeljevski,Modelo para Sistemas de Supervisão de Mercado ...,tese,Engenharia do Conhecimento,2021,Florianópolis,"Prof. José Leomar Todesco, Dr.","Prof. Alexandre Leopoldo Gonçalves, Dr.",A confiança na higidez dos mercados de capitai...,"['Mercado de Capitais', 'Mercado de Valores Mo...",The confidence in the integrity of capital mar...,"['Capital market', 'Securities Market', 'Marke...",{'contextualizacao': 'O mercado de capitais é ...,O modelo elaborado nest a pesquisa envolveu a ...,"[0.02262425608932972, 0.06360490620136261, 0.0...",-0.174124,0.159395,-0.060768
1,treino,IVAM GALVÃO FILHO,FRACTUS: APLICATIVO PARA APRENDIZAGEM DE FRAÇÕES,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Profª. Vania Ribas Ulbricht, Drª.","Profª. Elisa Maria Pivetta, Drª.",O objetivo principal desta pesquisa foi o dese...,"['Objetos de Aprendizagem.', 'Frações.', 'Apli...",The main objective of this research was the de...,"['Learning Objects.', 'Fractions.', 'App for L...",{'contextualizacao': 'O sistema educacional br...,O trabalho realizado pela organização TODOS PE...,"[-0.006245349999517202, 0.065089151263237, 0.0...",0.143998,0.263873,-0.055491
2,treino,MÁRCIO CRESCENCIO,MODELO DE UMA REDE COLABORATIVA SUPORTADA POR ...,tese,Engenharia do Conhecimento,2022,Florianópolis,"Prof. Alexandre Augusto Biz , Dr.","Prof. José Leomar Todesco , Dr.",A convergência entre o turismo e a cultura atr...,"['Sítios de Patrimônio Mundial', 'Gestão do tu...",The convergence between tourism and culture th...,"['World Heritage Sites', 'Tourism management',...",{'contextualizacao': 'O turismo se tornou uma ...,Esta tese identificou que o turismo possui um ...,"[0.024945586919784546, 0.04501194879412651, 0....",-0.111669,-0.167909,-0.015695
3,treino,Roseli Honorio,MODELO CONCEITUAL DE GOVERNANÇA DE DADOS COMO ...,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Prof. João Artur de Souza, Dr.","Profa. Patrícia de Sá Freire, Dra.",A humanidade passou por transformações e revol...,"['Governança de Dados', 'Governança do Conheci...",Humanity has undergone transformations and rev...,"['Data Governance', 'Knowledge Governance', 'F...",{'contextualizacao': 'A sociedade está atraves...,"Na Ind ústria 4.0 e Sociedade 5.0, as organiza...","[0.05032069981098175, 0.051356106996536255, 0....",-0.229669,0.045873,-0.059402
4,treino,José Tadeu Silva,Análise da contribuição da engenharia do conhe...,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Prof. Fernando A. Ostuni Gauthier, Dr.","Prof. Marcelo Macedo, Dr.",A presente dissertação aborda as questões emer...,"['comércio eletrônico', 'modelo de análise', '...",The present dissertation addresses the emergin...,"['e-commerce', 'analysis model', 'knowledge en...",{'contextualizacao': 'De acordo com Lemos (200...,A partir do objetivo geral de analisar as cont...,"[-0.0012473083334043622, 0.044789645820856094,...",-0.195246,0.141014,0.098894

In [36]:
import ast

df['introducao_dict'] = df['introducao'].apply(ast.literal_eval)

# Depois, crie as novas colunas extraindo os valores do dicionário
df['introducao_contextualizacao'] = df['introducao_dict'].apply(lambda x: x.get('contextualizacao', ''))
df['introducao_problematica'] = df['introducao_dict'].apply(lambda x: x.get('problematica', ''))
df['introducao_ineditismo'] = df['introducao_dict'].apply(lambda x: x.get('ineditismo', ''))
df['introducao_contribuicao'] = df['introducao_dict'].apply(lambda x: x.get('contribuição', ''))

# Remova a coluna temporária
df.drop(columns=['introducao_dict'], inplace=True)

df.head()

,modalidade,autor,titulo,tipo,area_de_concentracao,ano_de_publicacao,local,orientador,coorientador,resumo,...,introducao,conclusao,embedding,x,y,z,introducao_contextualizacao,introducao_problematica,introducao_ineditismo,introducao_contribuicao
id,,,,,,,,,,,,,,,,,,,,,
0,treino,Jorge Ivan Hmeljevski,Modelo para Sistemas de Supervisão de Mercado ...,tese,Engenharia do Conhecimento,2021,Florianópolis,"Prof. José Leomar Todesco, Dr.","Prof. Alexandre Leopoldo Gonçalves, Dr.",A confiança na higidez dos mercados de capitai...,...,{'contextualizacao': 'O mercado de capitais é ...,O modelo elaborado nest a pesquisa envolveu a ...,"[0.02262425608932972, 0.06360490620136261, 0.0...",-0.174124,0.159395,-0.060768,O mercado de capitais é fundamental para o cre...,"Os SSM, de maneira geral, usam os dado s prove...","De maneira inédita, portanto, este trabalho pa...","A contribuição desta pesquisa, portanto, está ..."
1,treino,IVAM GALVÃO FILHO,FRACTUS: APLICATIVO PARA APRENDIZAGEM DE FRAÇÕES,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Profª. Vania Ribas Ulbricht, Drª.","Profª. Elisa Maria Pivetta, Drª.",O objetivo principal desta pesquisa foi o dese...,...,{'contextualizacao': 'O sistema educacional br...,O trabalho realizado pela organização TODOS PE...,"[-0.006245349999517202, 0.065089151263237, 0.0...",0.143998,0.263873,-0.055491,O sistema educacional brasileiro passa por uma...,A deficiência na aprendizagem nas escolas de e...,,
2,treino,MÁRCIO CRESCENCIO,MODELO DE UMA REDE COLABORATIVA SUPORTADA POR ...,tese,Engenharia do Conhecimento,2022,Florianópolis,"Prof. Alexandre Augusto Biz , Dr.","Prof. José Leomar Todesco , Dr.",A convergência entre o turismo e a cultura atr...,...,{'contextualizacao': 'O turismo se tornou uma ...,Esta tese identificou que o turismo possui um ...,"[0.024945586919784546, 0.04501194879412651, 0....",-0.111669,-0.167909,-0.015695,O turismo se tornou uma das maiores indústrias...,"A convergência entre o turismo e a cultura, at...",O reconhecimento de PM atrai turistas adiciona...,Esses elementos de ligação do desenvolvimento ...
3,treino,Roseli Honorio,MODELO CONCEITUAL DE GOVERNANÇA DE DADOS COMO ...,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Prof. João Artur de Souza, Dr.","Profa. Patrícia de Sá Freire, Dra.",A humanidade passou por transformações e revol...,...,{'contextualizacao': 'A sociedade está atraves...,"Na Ind ústria 4.0 e Sociedade 5.0, as organiza...","[0.05032069981098175, 0.051356106996536255, 0....",-0.229669,0.045873,-0.059402,A sociedade está atravessando um momento de mu...,É nesse contexto que a Governanç a do Conhecim...,,
4,treino,José Tadeu Silva,Análise da contribuição da engenharia do conhe...,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Prof. Fernando A. Ostuni Gauthier, Dr.","Prof. Marcelo Macedo, Dr.",A presente dissertação aborda as questões emer...,...,{'contextualizacao': 'De acordo com Lemos (200...,A partir do objetivo geral de analisar as cont...,"[-0.0012473083334043622, 0.044789645820856094,...",-0.195246,0.141014,0.098894,"De acordo com Lemos (2003), sob qualquer aspec...","Para Vilaça e Araújo (2016), o conhecimento so...",,

In [41]:
# Criar o df apenas com os dados que tenham a modalidade treino
df_train = df[df['modalidade'] == 'treino']
df_train

,modalidade,autor,titulo,tipo,area_de_concentracao,ano_de_publicacao,local,orientador,coorientador,resumo,...,introducao,conclusao,embedding,x,y,z,introducao_contextualizacao,introducao_problematica,introducao_ineditismo,introducao_contribuicao
id,,,,,,,,,,,,,,,,,,,,,
0,treino,Jorge Ivan Hmeljevski,Modelo para Sistemas de Supervisão de Mercado ...,tese,Engenharia do Conhecimento,2021,Florianópolis,"Prof. José Leomar Todesco, Dr.","Prof. Alexandre Leopoldo Gonçalves, Dr.",A confiança na higidez dos mercados de capitai...,...,{'contextualizacao': 'O mercado de capitais é ...,O modelo elaborado nest a pesquisa envolveu a ...,"[0.02262425608932972, 0.06360490620136261, 0.0...",-0.174124,0.159395,-0.060768,O mercado de capitais é fundamental para o cre...,"Os SSM, de maneira geral, usam os dado s prove...","De maneira inédita, portanto, este trabalho pa...","A contribuição desta pesquisa, portanto, está ..."
1,treino,IVAM GALVÃO FILHO,FRACTUS: APLICATIVO PARA APRENDIZAGEM DE FRAÇÕES,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Profª. Vania Ribas Ulbricht, Drª.","Profª. Elisa Maria Pivetta, Drª.",O objetivo principal desta pesquisa foi o dese...,...,{'contextualizacao': 'O sistema educacional br...,O trabalho realizado pela organização TODOS PE...,"[-0.006245349999517202, 0.065089151263237, 0.0...",0.143998,0.263873,-0.055491,O sistema educacional brasileiro passa por uma...,A deficiência na aprendizagem nas escolas de e...,,
2,treino,MÁRCIO CRESCENCIO,MODELO DE UMA REDE COLABORATIVA SUPORTADA POR ...,tese,Engenharia do Conhecimento,2022,Florianópolis,"Prof. Alexandre Augusto Biz , Dr.","Prof. José Leomar Todesco , Dr.",A convergência entre o turismo e a cultura atr...,...,{'contextualizacao': 'O turismo se tornou uma ...,Esta tese identificou que o turismo possui um ...,"[0.024945586919784546, 0.04501194879412651, 0....",-0.111669,-0.167909,-0.015695,O turismo se tornou uma das maiores indústrias...,"A convergência entre o turismo e a cultura, at...",O reconhecimento de PM atrai turistas adiciona...,Esses elementos de ligação do desenvolvimento ...
3,treino,Roseli Honorio,MODELO CONCEITUAL DE GOVERNANÇA DE DADOS COMO ...,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Prof. João Artur de Souza, Dr.","Profa. Patrícia de Sá Freire, Dra.",A humanidade passou por transformações e revol...,...,{'contextualizacao': 'A sociedade está atraves...,"Na Ind ústria 4.0 e Sociedade 5.0, as organiza...","[0.05032069981098175, 0.051356106996536255, 0....",-0.229669,0.045873,-0.059402,A sociedade está atravessando um momento de mu...,É nesse contexto que a Governanç a do Conhecim...,,
4,treino,José Tadeu Silva,Análise da contribuição da engenharia do conhe...,dissertação,Engenharia do Conhecimento,2022,Florianópolis,"Prof. Fernando A. Ostuni Gauthier, Dr.","Prof. Marcelo Macedo, Dr.",A presente dissertação aborda as questões emer...,...,{'contextualizacao': 'De acordo com Lemos (200...,A partir do objetivo geral de analisar as cont...,"[-0.0012473083334043622, 0.044789645820856094,...",-0.195246,0.141014,0.098894,"De acordo com Lemos (2003), sob qualquer aspec...","Para Vilaça e Araújo (2016), o conhecimento so...",,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,treino,Rosani Cesário Pereira,Competências essenciais dos pregoeiros: um est...,dissertação,Gestão do Conhecimento,2023,Florianópolis,"Prof.a Édis Mafra Lapolli, Dr a.","Prof.a Gertrudes A. Dandolini , Dra.",O modelo de gestão que vem se consolidando na ...,...,"{'contextualizacao': 'A autora, Rosani Cesário...",A pesquisa conclui que as competências essenci...,"[0.03604484349489212, 0.046274762600660324, 0....",-0.049497,-0.208519,-0.222047,"A autora, Rosani Cesário Pereira, inicia a dis...",A pesquisa aborda a importância da função de p...,,
146,treino,Fabíola Provensi,Gestão do Conhecimento e Cultura de Segurança ...,dissertação,Gestão do Conhecimento,2023,Florianópolis,"Prof. Eduardo Juan Soriano Sierra, Dr.","Prof. Neri Dos Santos, Dr.","No âmbito deste estudo, no que tange à Cultura...",...,{'contextualizacao': 'A Saúde e Segurança no T...,O estudo realizado foi enriquecedor e motivado...,"[0.039430100470781326, 0.055613141506910324, 0...",-0.123317,-0.074993,-0.123015,"A Saúde e Segurança no Trabalho (SST), também ...","No contexto deste estudo, além de organização ...",,
147,treino,Maria Carolina Milani Caldas Sartor,Gestão feminina: a experiência de mulheres que...,tese,Gestão do Conhecimento,2023,Florianópolis,"Prof.a Édis Mafra Lapolli, Dra.","Prof.a Inara A. V. Willerding, Dra.",A entrada da mulher no mercado de trabalho e a...,...,{'contextualizacao': 'A presente pesquisa visa...,"A presente pesquisa, realizada com o objetivo ...","[0.056130435317754745, 0.025203583762049675, 0...",-0.002209,-0.331049,-0.153390,A presente pesquisa visa a compreender a atuaç...,A problemática se concentra nos desafios enfre...,Embora existam estudos sobre atitudes empreend...,A presente pesquisa se justifica por sua relev...
148,treino,Sergio Luiz Gargioni,MODELO OPERACIONAL DE EDUCAÇÃO CONTINUADA PARA...,tese,Gestão do Conhecimento,2023,Florianópolis – SC,"Professor Neri dos Santos, Dr. Ing.","Professor Gregório Jean Varvakis Rados, Dr. Ing.",Este trabalho de tese apresenta um modelo oper...,...,{'contextualizacao': 'O problema de pesquisa a...,Embora exista sempre espaço para pensar que co...,"[0.018794536590576172, 0.06826724857091904, -0...",0.021588,0.119867,0.174279,"O problema de pesquisa abordado nesta tese, re...","De fato, a experiência prática ficou restrita,...","Essa é uma lista de desejos impressionante, ma...",A realidade é que existem melhores métodos de ...
149,treino,Edegilson de Souza,A COMPLEXIDADE COMO SUPORTE À MODELAGEM DE COM...,tese,Gestão do Conhecimento,2023,Florianópolis,"Prof. Francisco Antonio Pereira Fialho, Dr.","Profa. Luciane Maria Fadel, Dra.",A implementação das novas metodologias de ensi...,...,{'contextualizacao': 'A educação do século 21 ...,A abordagem inovadora proposta neste estudo of...,"[0.04360678791999817, 0.05723390728235245, -0....",0.092158,0.018886,0.115306,A educação do século 21 é desafiadora e comple...,"Nesse sentido, torna-se relevante entender com...",Cumpre destacar que as competências docentes e...,"Dessa forma, este estudo explora as implicaçõe..."

In [37]:
index_name = "ppgegc_qa_method"
dimensions = 1536

In [42]:
client_qdrant.recreate_collection(
    collection_name=index_name,
    vectors_config=VectorParams(size=dimensions, distance=Distance.COSINE),
)

/tmp/ipykernel_17410/3122704942.py:1: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  client_qdrant.recreate_collection(

True

In [43]:
id = 0
points = []
for index, row in df_train.iterrows():
    id += 1
    autor = row.autor
    titulo = row.titulo
    tipo = row.tipo
    area_de_concentracao = row.area_de_concentracao
    ano_de_publicacao = row.ano_de_publicacao
    local = row.local
    orientador = row.orientador
    coorientador = row.coorientador
    resumo = row.resumo
    palavras_chave = row.palavras_chave
    abstract = row.abstract
    keywords = row.keywords
    introducao_contextualizacao = row.introducao_contextualizacao
    introducao_problematica = row.introducao_problematica
    introducao_ineditismo = row.introducao_ineditismo
    introducao_contribuicao = row.introducao_contribuicao
    conclusao = row.conclusao

    # Converta a string de embedding para uma lista de floats
    embedding = ast.literal_eval(row.embedding)

    points.append(PointStruct(id=id, vector=embedding,
                                payload={
                "autor": autor,
                "titulo": titulo,
                "tipo": tipo,
                "area_de_concentracao": area_de_concentracao,
                "ano_de_publicacao": ano_de_publicacao,
                "local": local,
                "orientador": orientador,
                "coorientador": coorientador,
                "resumo": resumo,
                "palavras_chave": palavras_chave,
                "abstract": abstract,
                "keywords": keywords, 
                "introducao_contextualizacao": introducao_contextualizacao,
                "introducao_problematica": introducao_problematica,
                "introducao_ineditismo": introducao_ineditismo,
                "introducao_contribuicao": introducao_contribuicao,
                "conclusao": conclusao}))
    
    if ((id % 50 ) == 0):
        operation_info = client_qdrant.upsert(
                         collection_name=index_name,
                         wait=True,
                         points=points
                    )
        points.clear()
        print("{} tese/dissertação indexada!!!".format(id))

if len(points) != 0:
  operation_info = client_qdrant.upsert(
                         collection_name=index_name,
                         wait=True,
                         points=points
                    )
  print("{} tese/dissertação indexada!!!".format(id))

print("Indexação terminada!!!")

50 tese/dissertação indexada!!!
100 tese/dissertação indexada!!!
105 tese/dissertação indexada!!!
Indexação terminada!!!